services:

  trunkstream:
    container_name: trunkstream
    image: docker.io/library/trunkstream-app
    command: uvicorn trunkstream.app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
      - ./uploads:/code/uploads
    environment:
      - TS_MONGOURL=${TS_MONGOURL}
    ports:
      - 8000:8000
      
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379

  tones_worker:
    container_name: tones_worker
    image: docker.io/library/trunkstream-app
    command: celery -A trunkstream.worker worker --loglevel=WARNING -Q tones -E -n tones@%%h
    volumes:
      - .:/code
      - ./uploads:/code/uploads
    environment:
      - TS_MONGOURL=${TS_MONGOURL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - FLOWER_UNAUTHENTICATED_API=True
      - TZ=US/Eastern
    depends_on:
      - trunkstream
      - redis

  flower:
    container_name: flower
    image: docker.io/library/trunkstream-app
    command: celery -A trunkstream.worker flower --port=5555
    ports:
      - 5556:5555
    environment:
      - TS_MONGOURL=${TS_MONGOURL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - FLOWER_UNAUTHENTICATED_API=True
      - TZ=US/Eastern
    depends_on:
      - trunkstream
      - redis
      - tones_worker
volumes:
  upload-volume: